platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_root = File.expand_path(File.join('..', ''))
  # Flutter tooling generates/updates the remaining Pod configuration.
end
